package com.cdut.studypro.daos;

import com.cdut.studypro.beans.CourseVideo;
import com.cdut.studypro.beans.CourseVideoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CourseVideoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_video
     *
     * @mbg.generated Tue Mar 31 13:05:28 CST 2020
     */
    long countByExample(CourseVideoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_video
     *
     * @mbg.generated Tue Mar 31 13:05:28 CST 2020
     */
    int deleteByExample(CourseVideoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_video
     *
     * @mbg.generated Tue Mar 31 13:05:28 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_video
     *
     * @mbg.generated Tue Mar 31 13:05:28 CST 2020
     */
    int insert(CourseVideo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_video
     *
     * @mbg.generated Tue Mar 31 13:05:28 CST 2020
     */
    int insertSelective(CourseVideo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_video
     *
     * @mbg.generated Tue Mar 31 13:05:28 CST 2020
     */
    List<CourseVideo> selectByExample(CourseVideoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_video
     *
     * @mbg.generated Tue Mar 31 13:05:28 CST 2020
     */
    CourseVideo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_video
     *
     * @mbg.generated Tue Mar 31 13:05:28 CST 2020
     */
    int updateByExampleSelective(@Param("record") CourseVideo record, @Param("example") CourseVideoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_video
     *
     * @mbg.generated Tue Mar 31 13:05:28 CST 2020
     */
    int updateByExample(@Param("record") CourseVideo record, @Param("example") CourseVideoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_video
     *
     * @mbg.generated Tue Mar 31 13:05:28 CST 2020
     */
    int updateByPrimaryKeySelective(CourseVideo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_video
     *
     * @mbg.generated Tue Mar 31 13:05:28 CST 2020
     */
    int updateByPrimaryKey(CourseVideo record);
}