package com.cdut.studypro.daos;

import com.cdut.studypro.beans.CourseFile;
import com.cdut.studypro.beans.CourseFileExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CourseFileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_file
     *
     * @mbg.generated Tue Mar 31 13:05:28 CST 2020
     */
    long countByExample(CourseFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_file
     *
     * @mbg.generated Tue Mar 31 13:05:28 CST 2020
     */
    int deleteByExample(CourseFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_file
     *
     * @mbg.generated Tue Mar 31 13:05:28 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_file
     *
     * @mbg.generated Tue Mar 31 13:05:28 CST 2020
     */
    int insert(CourseFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_file
     *
     * @mbg.generated Tue Mar 31 13:05:28 CST 2020
     */
    int insertSelective(CourseFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_file
     *
     * @mbg.generated Tue Mar 31 13:05:28 CST 2020
     */
    List<CourseFile> selectByExample(CourseFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_file
     *
     * @mbg.generated Tue Mar 31 13:05:28 CST 2020
     */
    CourseFile selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_file
     *
     * @mbg.generated Tue Mar 31 13:05:28 CST 2020
     */
    int updateByExampleSelective(@Param("record") CourseFile record, @Param("example") CourseFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_file
     *
     * @mbg.generated Tue Mar 31 13:05:28 CST 2020
     */
    int updateByExample(@Param("record") CourseFile record, @Param("example") CourseFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_file
     *
     * @mbg.generated Tue Mar 31 13:05:28 CST 2020
     */
    int updateByPrimaryKeySelective(CourseFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_file
     *
     * @mbg.generated Tue Mar 31 13:05:28 CST 2020
     */
    int updateByPrimaryKey(CourseFile record);
}