package com.cdut.studypro.daos;

import com.cdut.studypro.beans.TaskQuestion;
import com.cdut.studypro.beans.TaskQuestionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TaskQuestionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_question
     *
     * @mbg.generated Tue Mar 31 13:05:28 CST 2020
     */
    long countByExample(TaskQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_question
     *
     * @mbg.generated Tue Mar 31 13:05:28 CST 2020
     */
    int deleteByExample(TaskQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_question
     *
     * @mbg.generated Tue Mar 31 13:05:28 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_question
     *
     * @mbg.generated Tue Mar 31 13:05:28 CST 2020
     */
    int insert(TaskQuestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_question
     *
     * @mbg.generated Tue Mar 31 13:05:28 CST 2020
     */
    int insertSelective(TaskQuestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_question
     *
     * @mbg.generated Tue Mar 31 13:05:28 CST 2020
     */
    List<TaskQuestion> selectByExample(TaskQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_question
     *
     * @mbg.generated Tue Mar 31 13:05:28 CST 2020
     */
    TaskQuestion selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_question
     *
     * @mbg.generated Tue Mar 31 13:05:28 CST 2020
     */
    int updateByExampleSelective(@Param("record") TaskQuestion record, @Param("example") TaskQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_question
     *
     * @mbg.generated Tue Mar 31 13:05:28 CST 2020
     */
    int updateByExample(@Param("record") TaskQuestion record, @Param("example") TaskQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_question
     *
     * @mbg.generated Tue Mar 31 13:05:28 CST 2020
     */
    int updateByPrimaryKeySelective(TaskQuestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_question
     *
     * @mbg.generated Tue Mar 31 13:05:28 CST 2020
     */
    int updateByPrimaryKey(TaskQuestion record);
}