package com.cdut.studypro.beans;

import java.util.Date;

public class DiscussPost {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column discuss_post.id
     *
     * @mbg.generated Tue Mar 31 13:05:28 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column discuss_post.discuss_id
     *
     * @mbg.generated Tue Mar 31 13:05:28 CST 2020
     */
    private Integer discussId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column discuss_post.student_id
     *
     * @mbg.generated Tue Mar 31 13:05:28 CST 2020
     */
    private Integer studentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column discuss_post.record_time
     *
     * @mbg.generated Tue Mar 31 13:05:28 CST 2020
     */
    private Date recordTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column discuss_post.content
     *
     * @mbg.generated Tue Mar 31 13:05:28 CST 2020
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column discuss_post.id
     *
     * @return the value of discuss_post.id
     *
     * @mbg.generated Tue Mar 31 13:05:28 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column discuss_post.id
     *
     * @param id the value for discuss_post.id
     *
     * @mbg.generated Tue Mar 31 13:05:28 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column discuss_post.discuss_id
     *
     * @return the value of discuss_post.discuss_id
     *
     * @mbg.generated Tue Mar 31 13:05:28 CST 2020
     */
    public Integer getDiscussId() {
        return discussId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column discuss_post.discuss_id
     *
     * @param discussId the value for discuss_post.discuss_id
     *
     * @mbg.generated Tue Mar 31 13:05:28 CST 2020
     */
    public void setDiscussId(Integer discussId) {
        this.discussId = discussId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column discuss_post.student_id
     *
     * @return the value of discuss_post.student_id
     *
     * @mbg.generated Tue Mar 31 13:05:28 CST 2020
     */
    public Integer getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column discuss_post.student_id
     *
     * @param studentId the value for discuss_post.student_id
     *
     * @mbg.generated Tue Mar 31 13:05:28 CST 2020
     */
    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column discuss_post.record_time
     *
     * @return the value of discuss_post.record_time
     *
     * @mbg.generated Tue Mar 31 13:05:28 CST 2020
     */
    public Date getRecordTime() {
        return recordTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column discuss_post.record_time
     *
     * @param recordTime the value for discuss_post.record_time
     *
     * @mbg.generated Tue Mar 31 13:05:28 CST 2020
     */
    public void setRecordTime(Date recordTime) {
        this.recordTime = recordTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column discuss_post.content
     *
     * @return the value of discuss_post.content
     *
     * @mbg.generated Tue Mar 31 13:05:28 CST 2020
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column discuss_post.content
     *
     * @param content the value for discuss_post.content
     *
     * @mbg.generated Tue Mar 31 13:05:28 CST 2020
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discuss_post
     *
     * @mbg.generated Tue Mar 31 13:05:28 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", discussId=").append(discussId);
        sb.append(", studentId=").append(studentId);
        sb.append(", recordTime=").append(recordTime);
        sb.append(", content=").append(content);
        sb.append("]");
        return sb.toString();
    }
}