package com.cdut.studypro.beans;

import java.util.Date;

public class Discuss {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column discuss.id
     *
     * @mbg.generated Tue Mar 31 13:05:28 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column discuss.title
     *
     * @mbg.generated Tue Mar 31 13:05:28 CST 2020
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column discuss.teacher_id
     *
     * @mbg.generated Tue Mar 31 13:05:28 CST 2020
     */
    private Integer teacherId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column discuss.record_time
     *
     * @mbg.generated Tue Mar 31 13:05:28 CST 2020
     */
    private Date recordTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column discuss.course_id
     *
     * @mbg.generated Tue Mar 31 13:05:28 CST 2020
     */
    private Integer courseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column discuss.content
     *
     * @mbg.generated Tue Mar 31 13:05:28 CST 2020
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column discuss.id
     *
     * @return the value of discuss.id
     *
     * @mbg.generated Tue Mar 31 13:05:28 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column discuss.id
     *
     * @param id the value for discuss.id
     *
     * @mbg.generated Tue Mar 31 13:05:28 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column discuss.title
     *
     * @return the value of discuss.title
     *
     * @mbg.generated Tue Mar 31 13:05:28 CST 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column discuss.title
     *
     * @param title the value for discuss.title
     *
     * @mbg.generated Tue Mar 31 13:05:28 CST 2020
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column discuss.teacher_id
     *
     * @return the value of discuss.teacher_id
     *
     * @mbg.generated Tue Mar 31 13:05:28 CST 2020
     */
    public Integer getTeacherId() {
        return teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column discuss.teacher_id
     *
     * @param teacherId the value for discuss.teacher_id
     *
     * @mbg.generated Tue Mar 31 13:05:28 CST 2020
     */
    public void setTeacherId(Integer teacherId) {
        this.teacherId = teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column discuss.record_time
     *
     * @return the value of discuss.record_time
     *
     * @mbg.generated Tue Mar 31 13:05:28 CST 2020
     */
    public Date getRecordTime() {
        return recordTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column discuss.record_time
     *
     * @param recordTime the value for discuss.record_time
     *
     * @mbg.generated Tue Mar 31 13:05:28 CST 2020
     */
    public void setRecordTime(Date recordTime) {
        this.recordTime = recordTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column discuss.course_id
     *
     * @return the value of discuss.course_id
     *
     * @mbg.generated Tue Mar 31 13:05:28 CST 2020
     */
    public Integer getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column discuss.course_id
     *
     * @param courseId the value for discuss.course_id
     *
     * @mbg.generated Tue Mar 31 13:05:28 CST 2020
     */
    public void setCourseId(Integer courseId) {
        this.courseId = courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column discuss.content
     *
     * @return the value of discuss.content
     *
     * @mbg.generated Tue Mar 31 13:05:28 CST 2020
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column discuss.content
     *
     * @param content the value for discuss.content
     *
     * @mbg.generated Tue Mar 31 13:05:28 CST 2020
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discuss
     *
     * @mbg.generated Tue Mar 31 13:05:28 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", title=").append(title);
        sb.append(", teacherId=").append(teacherId);
        sb.append(", recordTime=").append(recordTime);
        sb.append(", courseId=").append(courseId);
        sb.append(", content=").append(content);
        sb.append("]");
        return sb.toString();
    }
}