package com.cdut.studypro.beans;

import java.util.Date;

public class StudentTask {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_task.id
     *
     * @mbg.generated Tue Mar 31 13:05:28 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_task.student_id
     *
     * @mbg.generated Tue Mar 31 13:05:28 CST 2020
     */
    private Integer studentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_task.task_id
     *
     * @mbg.generated Tue Mar 31 13:05:28 CST 2020
     */
    private Integer taskId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_task.score
     *
     * @mbg.generated Tue Mar 31 13:05:28 CST 2020
     */
    private Integer score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_task.record_time
     *
     * @mbg.generated Tue Mar 31 13:05:28 CST 2020
     */
    private Date recordTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_task.id
     *
     * @return the value of student_task.id
     *
     * @mbg.generated Tue Mar 31 13:05:28 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_task.id
     *
     * @param id the value for student_task.id
     *
     * @mbg.generated Tue Mar 31 13:05:28 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_task.student_id
     *
     * @return the value of student_task.student_id
     *
     * @mbg.generated Tue Mar 31 13:05:28 CST 2020
     */
    public Integer getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_task.student_id
     *
     * @param studentId the value for student_task.student_id
     *
     * @mbg.generated Tue Mar 31 13:05:28 CST 2020
     */
    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_task.task_id
     *
     * @return the value of student_task.task_id
     *
     * @mbg.generated Tue Mar 31 13:05:28 CST 2020
     */
    public Integer getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_task.task_id
     *
     * @param taskId the value for student_task.task_id
     *
     * @mbg.generated Tue Mar 31 13:05:28 CST 2020
     */
    public void setTaskId(Integer taskId) {
        this.taskId = taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_task.score
     *
     * @return the value of student_task.score
     *
     * @mbg.generated Tue Mar 31 13:05:28 CST 2020
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_task.score
     *
     * @param score the value for student_task.score
     *
     * @mbg.generated Tue Mar 31 13:05:28 CST 2020
     */
    public void setScore(Integer score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_task.record_time
     *
     * @return the value of student_task.record_time
     *
     * @mbg.generated Tue Mar 31 13:05:28 CST 2020
     */
    public Date getRecordTime() {
        return recordTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_task.record_time
     *
     * @param recordTime the value for student_task.record_time
     *
     * @mbg.generated Tue Mar 31 13:05:28 CST 2020
     */
    public void setRecordTime(Date recordTime) {
        this.recordTime = recordTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_task
     *
     * @mbg.generated Tue Mar 31 13:05:28 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", studentId=").append(studentId);
        sb.append(", taskId=").append(taskId);
        sb.append(", score=").append(score);
        sb.append(", recordTime=").append(recordTime);
        sb.append("]");
        return sb.toString();
    }
}