package com.cdut.studypro.beans;

public class TaskQuestion {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_question.id
     *
     * @mbg.generated Tue Mar 31 13:05:28 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_question.title
     *
     * @mbg.generated Tue Mar 31 13:05:28 CST 2020
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_question.item_a
     *
     * @mbg.generated Tue Mar 31 13:05:28 CST 2020
     */
    private String itemA;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_question.item_b
     *
     * @mbg.generated Tue Mar 31 13:05:28 CST 2020
     */
    private String itemB;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_question.item_c
     *
     * @mbg.generated Tue Mar 31 13:05:28 CST 2020
     */
    private String itemC;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_question.item_d
     *
     * @mbg.generated Tue Mar 31 13:05:28 CST 2020
     */
    private String itemD;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_question.answer
     *
     * @mbg.generated Tue Mar 31 13:05:28 CST 2020
     */
    private String answer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_question.task_id
     *
     * @mbg.generated Tue Mar 31 13:05:28 CST 2020
     */
    private Integer taskId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_question.score
     *
     * @mbg.generated Tue Mar 31 13:05:28 CST 2020
     */
    private Integer score;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_question.id
     *
     * @return the value of task_question.id
     *
     * @mbg.generated Tue Mar 31 13:05:28 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_question.id
     *
     * @param id the value for task_question.id
     *
     * @mbg.generated Tue Mar 31 13:05:28 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_question.title
     *
     * @return the value of task_question.title
     *
     * @mbg.generated Tue Mar 31 13:05:28 CST 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_question.title
     *
     * @param title the value for task_question.title
     *
     * @mbg.generated Tue Mar 31 13:05:28 CST 2020
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_question.item_a
     *
     * @return the value of task_question.item_a
     *
     * @mbg.generated Tue Mar 31 13:05:28 CST 2020
     */
    public String getItemA() {
        return itemA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_question.item_a
     *
     * @param itemA the value for task_question.item_a
     *
     * @mbg.generated Tue Mar 31 13:05:28 CST 2020
     */
    public void setItemA(String itemA) {
        this.itemA = itemA == null ? null : itemA.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_question.item_b
     *
     * @return the value of task_question.item_b
     *
     * @mbg.generated Tue Mar 31 13:05:28 CST 2020
     */
    public String getItemB() {
        return itemB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_question.item_b
     *
     * @param itemB the value for task_question.item_b
     *
     * @mbg.generated Tue Mar 31 13:05:28 CST 2020
     */
    public void setItemB(String itemB) {
        this.itemB = itemB == null ? null : itemB.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_question.item_c
     *
     * @return the value of task_question.item_c
     *
     * @mbg.generated Tue Mar 31 13:05:28 CST 2020
     */
    public String getItemC() {
        return itemC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_question.item_c
     *
     * @param itemC the value for task_question.item_c
     *
     * @mbg.generated Tue Mar 31 13:05:28 CST 2020
     */
    public void setItemC(String itemC) {
        this.itemC = itemC == null ? null : itemC.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_question.item_d
     *
     * @return the value of task_question.item_d
     *
     * @mbg.generated Tue Mar 31 13:05:28 CST 2020
     */
    public String getItemD() {
        return itemD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_question.item_d
     *
     * @param itemD the value for task_question.item_d
     *
     * @mbg.generated Tue Mar 31 13:05:28 CST 2020
     */
    public void setItemD(String itemD) {
        this.itemD = itemD == null ? null : itemD.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_question.answer
     *
     * @return the value of task_question.answer
     *
     * @mbg.generated Tue Mar 31 13:05:28 CST 2020
     */
    public String getAnswer() {
        return answer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_question.answer
     *
     * @param answer the value for task_question.answer
     *
     * @mbg.generated Tue Mar 31 13:05:28 CST 2020
     */
    public void setAnswer(String answer) {
        this.answer = answer == null ? null : answer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_question.task_id
     *
     * @return the value of task_question.task_id
     *
     * @mbg.generated Tue Mar 31 13:05:28 CST 2020
     */
    public Integer getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_question.task_id
     *
     * @param taskId the value for task_question.task_id
     *
     * @mbg.generated Tue Mar 31 13:05:28 CST 2020
     */
    public void setTaskId(Integer taskId) {
        this.taskId = taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_question.score
     *
     * @return the value of task_question.score
     *
     * @mbg.generated Tue Mar 31 13:05:28 CST 2020
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_question.score
     *
     * @param score the value for task_question.score
     *
     * @mbg.generated Tue Mar 31 13:05:28 CST 2020
     */
    public void setScore(Integer score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_question
     *
     * @mbg.generated Tue Mar 31 13:05:28 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", title=").append(title);
        sb.append(", itemA=").append(itemA);
        sb.append(", itemB=").append(itemB);
        sb.append(", itemC=").append(itemC);
        sb.append(", itemD=").append(itemD);
        sb.append(", answer=").append(answer);
        sb.append(", taskId=").append(taskId);
        sb.append(", score=").append(score);
        sb.append("]");
        return sb.toString();
    }
}